name: Extract tar.xz File on macOS

on:
 push:
    branches:
      - main

jobs:
 extract:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract tarball file
      run: tar -xzf mesa-24.0.2.tar.xz
