name: Extract tar.xz File on macOS

on:
 push:
    branches:
      - main

jobs:
 extract:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract tarball file
      run: git clone https://gitlab.freedesktop.org/mesa/mesa
           cd mesa
           meson setup build -Dgallium-drivers=zink,iris,swrast -Dvulkan-drivers= --prefix=~/mesa-drivers
           ninja -C build install

